name: 'verify-build'

on:
  push:
    tags:
      - '*'
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  maven:
    name: 'maven-build'
    runs-on: ubuntu-latest
    env:
      MVN_SETTINGS_TEMPLATE_FILE: .mvn/settings.xml.tmpl
      MVN_SETTINGS_FILE: .mvn/settings.xml
      POM_FILE: pom.xml
    steps:
      # Checkout the repository to the GitHub Actions runner
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Prepare maven settings
        run: |
          sed -e "s/GH_REPO/${{ env.GITHUB_REPOSITORY }}/g" ${MVN_SETTINGS_TEMPLATE_FILE} > ${MVN_SETTINGS_FILE}
          sed -e "s/GH_DEPLOY_USERNAME/${{ env.GITHUB_REPOSITORY_OWNER }}/g" ${MVN_SETTINGS_TEMPLATE_FILE} > ${MVN_SETTINGS_FILE}
          sed -e "s/GH_DEPLOY_TOKEN/${{ secrets.GITHUB_TOKEN }}/g" ${MVN_SETTINGS_TEMPLATE_FILE} > ${MVN_SETTINGS_FILE}

      - name: Prepare release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mvn -s ${MVN_SETTINGS_FILE} release:prepare -DreleaseVersion=${{ github.ref_name }} -Dresume=false -DpushChanges=false || true

      - name: Deploy
        run: |
          mvn -s ${MVN_SETTINGS_FILE} --batch-mode deploy -Dlicense.skip=true

      - name: prepare artifact
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd target/components/packages
          cp *.zip ${{ github.event.repository.name }}-${{ github.ref_name }}.zip
          ls -lah

      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: target/components/packages/${{ github.event.repository.name }}-${{ github.ref_name }}.zip
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
